from typing import Protocol

from domain.entities import Expense, Payment


class ExpenseRepository(Protocol):
  async def save(self, expense: Expense) -> None: ...
  async def find_by_id(self, expense_id: str) -> Expense | None: ...
  async def find_by_month(self, guild_id: str, month: str) -> list[Expense]: ...
  async def update(self, expense: Expense) -> None: ...
  async def delete(self, expense_id: str) -> None: ...
  async def delete_by_user(self, guild_id: str, user_id: str) -> list[Expense]: ...


class PaymentRepository(Protocol):
  async def save(self, payment: Payment) -> None: ...
  async def find_by_month(self, guild_id: str, month: str) -> list[Payment]: ...
  async def delete_by_user(self, guild_id: str, user_id: str) -> list[Payment]: ...
